version: '2'
services:
  jekyll:
    build:
      context: "./"
      dockerfile: "Dockerfile"
    volumes:
      - ./:/usr/src/app
    ports:
      - "4000:4000"
    environment:
      - JEKYLL_ENV=development
    command:
      serve --watch --safe --incremental --force_polling --host 0.0.0.0