#!/bin/bash

set -e

if [[ -n "${RF_WEBSITE_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
"Usage: $(basename "$0")
Login to the jekyll container.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
      cd /opt/website && docker-compose run -p 4000:4000 --rm --entrypoint /bin/bash jekyll
    fi
fi