#!/bin/bash

set -e

if [[ -n "${RF_WEBSITE_DEBUG}" ]]; then
    set -x
fi

DIR="$(dirname "$0")"

function usage() {
    echo -n \
"Usage: $(basename "$0")
Start and stop jekyll server.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
      cd /opt/website && docker-compose up jekyll
    fi
fi