#!/bin/bash

set -e

if [[ -n "${RF_WEBSITE_DEBUG}" ]]; then
    set -x
fi

DIR="$(dirname "$0")"

function usage() {
    echo -n \
"Usage: $(basename "$0") 
Setup the development environment.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
      vagrant up --provision
      vagrant ssh -c "/opt/website/scripts/server"
    fi
fi